"""Base extractor for all data extractors.

Provides shared functionality (source metadata, file header generation)
so country-specific extractors only implement extract() and metadata methods.
"""

from abc import ABC, abstractmethod
from datetime import datetime

from fastpii.data.base import DataSource


class BaseExtractor(ABC):
    """Abstract base for all data extractors.

    Subclasses must implement:
        - extract(): perform the data extraction
        - get_source_url(): return the source URL
        - get_license(): return the data license

    Attributes:
        country_code: ISO 3166-1 alpha-2 code (e.g., 'CZ', 'SK', 'PL').
    """

    country_code: str

    @abstractmethod
    def extract(self) -> object:
        """Perform the data extraction and return the raw data."""

    @abstractmethod
    def get_source_url(self) -> str:
        """Return URL of the data source."""

    @abstractmethod
    def get_license(self) -> str:
        """Return the data license (e.g., 'Public domain', 'ODbL')."""

    def get_source(self, entry_count: int) -> DataSource:
        """Return data source metadata.

        Args:
            entry_count: number of entries in the extracted dataset.
        """
        return DataSource(
            name=f"{self.country_code} {self._data_type()}",
            url=self.get_source_url(),
            license=self.get_license(),
            last_updated=datetime.now(),
            entry_count=entry_count,
        )

    def _data_type(self) -> str:
        """Human-readable data type name for source metadata."""
        return "Data"

    def _write_header(self, f: object, source: DataSource) -> None:
        """Write standard file header with source metadata.

        Args:
            f: file handle open for writing.
            source: DataSource metadata.
        """
        f.write("# Auto-generated by FastPII data extractor\n")
        f.write(f"# Country: {self.country_code}\n")
        f.write(f"# Source: {source.url}\n")
        f.write(f"# License: {source.license}\n")
        f.write(f"# Extracted: {source.last_updated.isoformat()}\n")
        f.write(f"# Entries: {source.entry_count}\n\n")