# Auto-generated by FastPII data extractor
# Country: CZ
# Source: https://www.mfcr.cz/
# License: Public domain
# Extracted: 2026-06-29T12:23:13.176576
# Entries: 7

VALID_INSURANCE_CODES: set[str] = {
    "111",
    "201",
    "205",
    "207",
    "209",
    "211",
    "213",
}

INSURANCE_NAMES: dict[str, str] = {
    "111": "VZP (Všeobecná zdravotní pojišťovna)",
    "201": "ZP MVČR (Zdravotní pojišťovna Ministerstva vnitra ČR)",
    "205": "ČPZP (Česká průmyslová zdravotní pojišťovna)",
    "207": "OZP (Oborová zdravotní pojišťovna)",
    "209": "RBP (Rytířská zdravotní pojišťovna)",
    "211": "VoZP (Vojenská zdravotní pojišťovna)",
    "213": "ZPŠ (Zdravotní pojišťovna Škoda)",
}
