#!/usr/bin/env python3
"""Extract Czech postal codes from Česká pošta customer outputs.

Downloads the PSČ ZIP file from Česká pošta, parses the semicolon-separated
CSV inside, and generates a Python data module for postal codes.

Usage:
    python scripts/data/extract_cz_posta_psc.py

Output:
    src/fastpii/countries/cz/data/_data/postal_codes.py

Source:
    https://www.ceskaposta.cz/ke-stazeni/zakaznicke-vystupy

License: CC-BY 4.0 (via RÚIAN/NKOD open data catalog)
"""

import csv
import io
import sys
import tempfile
import zipfile
from datetime import datetime
from pathlib import Path
from typing import IO

sys.path.insert(0, "src")

try:
    import requests
except ImportError:
    print("Error: requests is required.")
    print("Install with: pip install requests")
    sys.exit(1)

from fastpii.data.base import DataSource


PSC_URL = "https://www.ceskaposta.cz/documents/d/guest/csv_psc_a-zip?download=true"


class CzechPostaPscExtractor:
    """Extract Czech postal codes from Česká pošta CSV data."""

    country_code: str = "CZ"

    def __init__(self) -> None:
        self._postal_codes: set[str] | None = None

    def extract(self) -> set[str]:
        """Download and parse Česká pošta PSČ CSV. Returns postal codes set."""
        if self._postal_codes is not None:
            return self._postal_codes

        postal_codes: set[str] = set()

        try:
            with tempfile.TemporaryDirectory() as temp_dir:
                temp_path = Path(temp_dir)
                zip_path = temp_path / "posta_psc.zip"

                response = requests.get(PSC_URL, timeout=300)
                response.raise_for_status()
                _ = zip_path.write_bytes(response.content)
                print(f"Downloaded ZIP from {PSC_URL}")

                with zipfile.ZipFile(zip_path) as archive:
                    csv_names = [
                        name for name in archive.namelist()
                        if name.lower().endswith(".csv")
                    ]
                    if not csv_names:
                        print("Error: ZIP archive does not contain any CSV files.")
                        sys.exit(1)

                    csv_name = csv_names[0]
                    print(f"Parsing {csv_name}...")

                    with archive.open(csv_name) as csv_file:
                        raw = csv_file.read()

                    # Try UTF-8 first, fall back to windows-1250
                    try:
                        content = raw.decode("utf-8-sig")
                    except UnicodeDecodeError:
                        content = raw.decode("windows-1250")

                    reader = csv.DictReader(io.StringIO(content), delimiter=";")

                    for row in reader:
                        psc = row.get("PSC", "").strip()
                        if psc and psc.isdigit() and len(psc) == 5:
                            postal_codes.add(psc)

        except requests.RequestException as exc:
            print(f"Error: Failed to download Česká pošta ZIP: {exc}")
            sys.exit(1)
        except zipfile.BadZipFile as exc:
            print(f"Error: Invalid ZIP archive downloaded: {exc}")
            sys.exit(1)
        except OSError as exc:
            print(f"Error: Failed to process data: {exc}")
            sys.exit(1)

        self._postal_codes = postal_codes
        print(f"Found {len(postal_codes)} postal codes")

        if not postal_codes:
            print("Warning: No postal codes were extracted.")

        return postal_codes

    def get_source_url(self) -> str:
        return "https://www.ceskaposta.cz/ke-stazeni/zakaznicke-vystupy"

    def get_license(self) -> str:
        return "CC-BY 4.0"

    def save(self, output_path: str) -> None:
        """Extract and save postal codes data file."""
        postal_codes = self.extract()

        source = DataSource(
            name="CZ Postal Codes",
            url=self.get_source_url(),
            license=self.get_license(),
            last_updated=datetime.now(),
            entry_count=len(postal_codes),
        )

        with open(output_path, "w") as f:
            self._write_header(f, source)
            _ = f.write("POSTAL_CODES: set[str] = {\n")
            for psc in sorted(postal_codes):
                _ = f.write(f'    "{psc}",\n')
            _ = f.write("}\n")

        print(f"Extracted {len(postal_codes)} postal codes to {output_path}")

    def _write_header(self, f: IO[str], source: DataSource) -> None:
        _ = f.write("# Auto-generated by FastPII data extractor\n")
        _ = f.write(f"# Country: {self.country_code}\n")
        _ = f.write(f"# Source: {source.url}\n")
        _ = f.write(f"# License: {source.license}\n")
        _ = f.write(f"# Extracted: {source.last_updated.isoformat()}\n")
        _ = f.write(f"# Entries: {source.entry_count}\n\n")


if __name__ == "__main__":
    output = "src/fastpii/countries/cz/data/_data/postal_codes.py"
    extractor = CzechPostaPscExtractor()
    extractor.save(output)