"""Tests for fastpii.data.extractors module."""

import tempfile
from pathlib import Path

import pytest

from fastpii.data.base import DataSource
from fastpii.data.extractors.base import BaseExtractor
from fastpii.data.extractors.bank_codes import BankCodesExtractor
from fastpii.data.extractors.cities import CitiesExtractor
from fastpii.data.extractors.postal_codes import PostalCodesExtractor
from fastpii.data.extractors.names import NamesExtractor


class StubExtractor(BaseExtractor):
    """Concrete stub for testing BaseExtractor."""

    country_code = "XX"

    def extract(self) -> dict[str, str]:
        return {"0100": "Test Bank"}

    def get_source_url(self) -> str:
        return "https://example.com"

    def get_license(self) -> str:
        return "MIT"


class TestBaseExtractor:
    def test_abstract_cannot_instantiate(self):
        with pytest.raises(TypeError):
            BaseExtractor()

    def test_concrete_subclass(self):
        ext = StubExtractor()
        assert ext.country_code == "XX"
        assert ext.extract() == {"0100": "Test Bank"}
        assert ext.get_source_url() == "https://example.com"
        assert ext.get_license() == "MIT"

    def test_get_source(self):
        ext = StubExtractor()
        source = ext.get_source(entry_count=42)
        assert isinstance(source, DataSource)
        assert source.name == "XX Data"
        assert source.url == "https://example.com"
        assert source.license == "MIT"
        assert source.entry_count == 42

    def test_data_type_default(self):
        ext = StubExtractor()
        assert ext._data_type() == "Data"

    def test_write_header(self):
        ext = StubExtractor()
        source = DataSource(
            name="XX Data", url="https://example.com", license="MIT",
            last_updated=__import__("datetime").datetime(2025, 1, 15), entry_count=42,
        )
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            ext._write_header(f, source)
            path = Path(f.name)

        content = path.read_text()
        assert "# Auto-generated by FastPII data extractor" in content
        assert "# Country: XX" in content
        assert "# Source: https://example.com" in content
        assert "# License: MIT" in content
        assert "# Entries: 42" in content
        path.unlink()


class TestBankCodesExtractor:
    def test_abstract_cannot_instantiate(self):
        with pytest.raises(TypeError):
            BankCodesExtractor()

    class CzechStub(BankCodesExtractor):
        country_code = "CZ"

        def extract(self) -> dict[str, str]:
            return {"0100": "ČNB", "0800": "Česká spořitelna"}

        def get_source_url(self) -> str:
            return "https://www.czso.cz/"

        def get_license(self) -> str:
            return "Public domain"

    def test_extract(self):
        ext = self.CzechStub()
        data = ext.extract()
        assert data == {"0100": "ČNB", "0800": "Česká spořitelna"}

    def test_data_type(self):
        ext = self.CzechStub()
        assert ext._data_type() == "Bank Codes"

    def test_save(self):
        ext = self.CzechStub()
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            ext.save(f.name)
            path = Path(f.name)

        content = path.read_text()
        assert "VALID_BANK_CODES" in content
        assert "BANK_NAMES" in content
        assert '"0100"' in content
        assert '"0800"' in content
        assert "ČNB" in content
        path.unlink()


class TestCitiesExtractor:
    def test_abstract_cannot_instantiate(self):
        with pytest.raises(TypeError):
            CitiesExtractor()

    class CzechStub(CitiesExtractor):
        country_code = "CZ"

        def extract(self) -> set[str]:
            return {"praha", "brno", "ostrava"}

        def get_source_url(self) -> str:
            return "https://download.geofabrik.de/"

        def get_license(self) -> str:
            return "ODbL"

    def test_extract(self):
        ext = self.CzechStub()
        data = ext.extract()
        assert "praha" in data
        assert len(data) == 3

    def test_data_type(self):
        ext = self.CzechStub()
        assert ext._data_type() == "Cities"

    def test_save(self):
        ext = self.CzechStub()
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            ext.save(f.name)
            path = Path(f.name)

        content = path.read_text()
        assert "CITIES" in content
        assert '"praha"' in content
        assert "# License: ODbL" in content
        path.unlink()


class TestPostalCodesExtractor:
    def test_abstract_cannot_instantiate(self):
        with pytest.raises(TypeError):
            PostalCodesExtractor()

    class CzechStub(PostalCodesExtractor):
        country_code = "CZ"

        def extract(self) -> set[str]:
            return {"11000", "60200"}

        def get_source_url(self) -> str:
            return "https://download.geofabrik.de/"

        def get_license(self) -> str:
            return "ODbL"

    def test_extract(self):
        ext = self.CzechStub()
        data = ext.extract()
        assert "11000" in data

    def test_data_type(self):
        ext = self.CzechStub()
        assert ext._data_type() == "Postal Codes"

    def test_save(self):
        ext = self.CzechStub()
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            ext.save(f.name)
            path = Path(f.name)

        content = path.read_text()
        assert "POSTAL_CODES" in content
        assert '"11000"' in content
        path.unlink()


class TestNamesExtractor:
    def test_abstract_cannot_instantiate(self):
        with pytest.raises(TypeError):
            NamesExtractor()

    class CzechStub(NamesExtractor):
        country_code = "CZ"

        def extract(self) -> dict[str, set[str]]:
            return {"male": {"Jan", "Petr"}, "female": {"Jana", "Petra"}}

        def get_source_url(self) -> str:
            return "https://www.czso.cz/"

        def get_license(self) -> str:
            return "Public domain"

    def test_extract(self):
        ext = self.CzechStub()
        data = ext.extract()
        assert "male" in data
        assert "female" in data
        assert "Jan" in data["male"]

    def test_data_type(self):
        ext = self.CzechStub()
        assert ext._data_type() == "Names"

    def test_save(self):
        ext = self.CzechStub()
        with tempfile.TemporaryDirectory() as tmpdir:
            male_path = Path(tmpdir) / "names_male.py"
            female_path = Path(tmpdir) / "names_female.py"
            ext.save(str(male_path), str(female_path))

            male_content = male_path.read_text()
            assert "MALE_NAMES" in male_content
            assert '"jan"' in male_content

            female_content = female_path.read_text()
            assert "FEMALE_NAMES" in female_content
            assert '"jana"' in female_content