# Auto-generated by FastPII data extractor
# Country: CZ
# Source: https://www.czso.cz/csu/cz/bankovni-kody
# License: Public domain
# Extracted: 2026-06-29
# Entries: 0 (placeholder — run extract_cz_bank_codes.py to populate)

BANK_NAMES: dict[str, str] = {}