# Auto-generated by FastPII data extractor
# Country: CZ
# Source: https://download.geofabrik.de/europe/czech-republic.html
# License: ODbL
# Extracted: 2026-06-29
# Entries: 0 (placeholder — run extract_cz_cities.py to populate)

CITIES: set[str] = set()