# Auto-generated by FastPII data extractor
# Country: CZ
# Source: https://www.czso.cz/csu/cz/aha/jmena_rodne
# License: Public domain
# Extracted: 2026-06-29
# Entries: 0 (placeholder — run extract_cz_names.py to populate)

FEMALE_NAMES: set[str] = set()